project:
  type: website

website:
  title: "Ana Elisa Lopez-Miranda"
  navbar:
    background: "#2F3D2A"
    foreground: "#E6E6E6"
    search: true
    right:
      - icon: github
        href: https://github.com/AnaElisaLopezMiranda
      - icon: linkedin
        href: https://www.linkedin.com/in/ana-elisa-lopez-miranda
        target: _blank
      - icon: envelope
        href: mailto:a.lopez.miranda@mail.utoronto.ca 
    left:
      - href: index.qmd
        text: Home
      - text: CV
        href: cv.pdf
        target: _blank
      - href: teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
  page-footer: |
    Last updated December 2025  
    Â© 2026 Ana Elisa Lopez-Miranda

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



